### ISSUE TITLE
missing cordova.js in index.html

### ISSUE THREAD

**Issue by inyourhands** [vuetifyjs/cordova#1]
Thank you for your efforts.
However, the deviceready event is not fired because the cordova.js file is not included.
Please include cordova.js in index.html file.
<br/>
<script type="text/javascript" src="cordova.js"></script>

**Comment by cairinmichie** [comment]
Thank you for bringing this up, I haven't included the code for managing the device ready event yet, it is the next thing on the todo list. I will update you when it has been completed.

**Comment by cairinmichie** [comment]
Although it should be noted that the device ready event does get fired even if you don't add `<script type="text/javascript" src="cordova.js"></script>` in your index.html.

**Comment by cairinmichie** [comment]
Fixed with pull request #6.

**Comment by inyourhands** [comment]
It works perfectly.
Thank you. ^ ^*
