### ISSUE TITLE
v-icon doesn't show up when app is offline

### ISSUE THREAD

**Issue by wyattis** [vuetifyjs/cordova#11]
It appears that the default webpack configuration uses a CDN for the Material Design icons which means that apps break when they are offline. It seems like the Material Design icons should be bundled along with the other app resources by default.

**Comment by cairinmichie** [comment]
Can you provide a reproduction? Screenshot of it running on android/ios should suffice.

I don't have this issue when the app is running within cordova, only when running the dev server, which makes sense.

**Comment by wyattis** [comment]
To reproduce:
1. Turn off device network
2. Uninstall previous app version (just in case cached fonts aren't removed? idk)
3. Run `npm run build`

The Material Design font will fail to load without the internet and the icons will look like this:

![image](https://user-images.githubusercontent.com/13564267/38033222-90d084fe-326d-11e8-8a65-bd7adf7d4a78.png)

Turning on the internet and restarting the app fixes the issue and makes it work even when the device is offline because the fonts are cached. The app should look like this:

![image](https://user-images.githubusercontent.com/13564267/38033553-49349c38-326e-11e8-9084-eb3543fdb9ca.png)

**Comment by cairinmichie** [comment]
How often are you going to install an app from the play store while you're offline??

**Comment by wyattis** [comment]
It's my opinion that apps should display correctly even when they are not connected to the internet. The fonts won't load until the app has started and it's plausible that there will be a gap between downloading an app and running it for the first time.

IMO, it's shortsighted to think that a mobile app shouldn't be self-contained unless explicitly designed to depend on the internet.

Anyway, my particular use case involves collecting data offline and won't involve the play store at all. Tablets will be offline for the majority of the time the app is running so I'll need to find a solution to this regardless.

**Comment by cairinmichie** [comment]
I don't have time to fix a bug like this at the moment, but you're more than welcome to submit a PR if you manage to fix it.

**Comment by rogerriche** [comment]
Should be able to download the icon font and include it with stylus or sass.  Doesn't have to be sourced from the cdn.

**Comment by mcfarljw** [comment]
I had this issue as well and I highly recommend including the font locally while using webfontloader (https://github.com/typekit/webfontloader) to make sure the font loads before hiding the splashscreen to prevent any screen flashing.

**Comment by appurist** [comment]
You can just store them locally and reference them with local paths. See [this stackoverflow article](https://stackoverflow.com/questions/37270835/how-to-host-material-icons-offline) for more.

**Comment by cairinmichie** [comment]
Adding that to the readme, and closing.
