### ISSUE TITLE
Iphone X white lines

### ISSUE THREAD

**Issue by DevelopFer** [vuetifyjs/cordova#15]
Hello I think this project is awesome however I've been struggling for too long trying to adapt my project to the iphone X; I've added the viewport tag but I still can't get rid of those lines.. is there anybody that have achieve that..thank you so much

**Comment by cairinmichie** [comment]
Try the steps listed [here](https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator).

**Comment by cairinmichie** [comment]
Also, read the readme.
