### ISSUE TITLE
Error on npm install 

### ISSUE THREAD

**Issue by shaqaruden** [vuetifyjs/cordova#16]
package.json error causes npm install to fail. There is an extra semi-colon at the end of devDependencies after  "webpack-cli": "^2.0.12". Removing it allows npm install to run

`  "webpack-cli": "^2.0.12",
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },`
FIXED
`  "webpack-cli": "^2.0.12",
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  }`

**Comment by cairinmichie** [comment]
Thanks.
