### ISSUE TITLE
CordovaError: Error validating package name.

### ISSUE THREAD

**Issue by Thebigbignooby** [vuetifyjs/cordova#2]
package name cannot have hyphens eg: `com.some-n-thing.something` isn't accepted

**Comment by Thebigbignooby** [comment]
This can be changed manually on line 2 in `config.xml`

**Comment by cairinmichie** [comment]
This is because `-` is not allowed in Android package names. You can however use a `_` in its place. [Naming conventions for packages](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) will be added to the readme.
