### ISSUE TITLE
How to reference cordova object

### ISSUE THREAD

**Issue by firesharkstudios** [vuetifyjs/cordova#26]
I'm wanting to access a Cordova plugin programmatically.  This is normally done with cordova.plugins; however, this build process results in cordova being undefined.

Is there a recommended way to get a cordova object reference to access cordova.plugins with this template?

**Comment by cairinmichie** [comment]
There are two ways I would recommend:

1. In the `.vue` files you can simply define the global cordova object from within your script:

```
<script>
/* global cordova */
export default {
    data () {
      return {
        cordova: cordova
      }
    },
    methods: {
      method1 () {
        console.log(this.cordova, ' is the same as ', cordova)
      }
    }
}
</script>
```
2. Use [Vue-cordova](http://kartsims.github.io/vue-cordova/). In my experience using this method the only plugins you will be able to get are the supported plugins. So I normally just use this for lifecycle hooks etc and use the global method I mentioned above for plugins.

Note that these will only work after the deviceready event has fired.

**Comment by firesharkstudios** [comment]
Perfect, thanks

**Comment by firesharkstudios** [comment]
Actually, I think the part I was missing was adding this to index.html.  Was assuming that this was already included with the webpack setup but I guess not.

  <script src="cordova.js"></script>

**Comment by cairinmichie** [comment]
Oh no that is added programatically in main.js.

```
if (window.location.protocol === 'file:' || window.location.port === '3000') {
  var cordovaScript = document.createElement('script')
  cordovaScript.setAttribute('type', 'text/javascript')
  cordovaScript.setAttribute('src', 'cordova.js')
  document.body.appendChild(cordovaScript)
}
```

**Comment by firesharkstudios** [comment]
Ahhh, that explains it.  I'm porting a web app to Cordova that already had a main.js -- I had replaced it.  Thanks for the clarification.
