### ISSUE TITLE
White screen why?

### ISSUE THREAD

**Issue by luizmagao** [vuetifyjs/cordova#29]
Because when I generate the apk and execute it is white screen

**Comment by Mataninja** [comment]
I have the same problem, I need help.  The problem mostly occurs on the Android version less than 7

**Comment by luizmagao** [comment]
This actually occurs when you run

> npm run android or npm run bowser

If you run

> npm run dev

Everything is normal because this is a problem that is inside the webpack, but I do not know how to do it.

- - - -- 

Na verdade isso ocorre quando você roda

> npm run android ou npm run bowser

Se você rodar 

> npm run dev

Tudo ocorre normal, porque isso é um problema que está dentro do webpack, só que eu não sei como fazer para ajeitar.

**Comment by cairinmichie** [comment]
Try https://github.com/vuetifyjs/vue-cli-plugin-vuetify .
