### ISSUE TITLE
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'

### ISSUE THREAD

**Issue by bezblue** [vuetifyjs/cordova#31]
Check dependencies
Code Signing Error: Signing for "my-project3" requires a development team. Select a development team in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'

** ARCHIVE FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
(node:1251) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/bezblue/Desktop/my-project3/platforms/ios/cordova/build-debug.xcconfig,-workspace,my-project3.xcworkspace,-scheme,my-project3,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,my-project3.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/bezblue/Desktop/my-project3/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/bezblue/Desktop/my-project3/platforms/ios/build/sharedpch
(node:1251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cairinmichie** [comment]
Go to xcode and use a signing certificate. This has nothing to do with this plugin.
