### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by gregos919** [vuetifyjs/cordova#36]
Getting an node error as on image below whenever I try to run `npm run build` or `npm run android`.
postcss-merge-rules@2.1.2 and its using postcss@5.2.18
cssnano@3.10.0
![image](https://user-images.githubusercontent.com/10901045/46402925-5b922800-c701-11e8-9452-006bd292de3a.png)

**Comment by ssendev** [comment]
the latest commits broke it. use 
```
vue init 'vuetifyjs/cordova#8febda945530bbe0bce390a28d358d221db4dfad'
```
to work around it temporarily

**Comment by template01** [comment]
@ssendev the commit indeed works! 
Nice. Would be great to see a patch on this :)

**Comment by Isaac2** [comment]
I can also confirm that using:
`vue init 'vuetifyjs/cordova#8febda945530bbe0bce390a28d358d221db4dfad' as @ssendev suggested works

**Comment by cairinmichie** [comment]
Use https://github.com/vuetifyjs/vue-cli-plugin-vuetify .
