### ISSUE TITLE
npm run build node err

### ISSUE THREAD

**Issue by PolanZ** [vuetifyjs/cordova#38]
```
> node build/build.js

(node:15344) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: decl.moveTo is not a function
```

I'm not find the decl.moveTo function

**Comment by fguillain** [comment]
you have to update several libs in package.json.

**Comment by qq690712575** [comment]
metoo
npm run android

![image](https://user-images.githubusercontent.com/17699491/48297300-d9efa000-e4df-11e8-9f8c-f6244b3b1609.png)

**Comment by farukzahra** [comment]
Same here!

**Comment by farukzahra** [comment]
https://github.com/vuetifyjs/cordova/issues/36

**Comment by cairinmichie** [comment]
Use https://github.com/vuetifyjs/vue-cli-plugin-vuetify.
