### ISSUE TITLE
Webpack dynamic import not working after andoid compile

### ISSUE THREAD

**Issue by mardonedias** [vuetifyjs/cordova#39]
Good night,

I'm having a little problem, when I compile the project for the android, the routes and components that have the **dynamic import** (_webpack spliting code_) does not work. It's as if _the android app does not recognize the dynamic import of these components_.

can anybody help me.

**Comment by cairinmichie** [comment]
This plugin is deprecated. Use https://github.com/vuetifyjs/vue-cli-plugin-vuetify and there are instructions there for cordova. Dynamic imports work with that version
