### ISSUE TITLE
Running npm run android thows java.lang.IllegalStateException: compileSdkVersion is not specified. Widget config error in config.xml?

### ISSUE THREAD

**Issue by acacha** [vuetifyjs/cordova#4]
It seems the are some errors in config.xml file:

- id is not set (blank string)
- Is necessary  android-versionCode="1"??? ti throws another error:

Failure [INSTALL_FAILED_VERSION_DOWNGRADE] ...

With:

```
<widget id="io.cordova.hellocordova" ios-CFBundleVersion="1" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
```

all works smoothly!

**Comment by cairinmichie** [comment]
Did you configure the reverse domain name when initialising the project? That would have filled in the id.

**Comment by ksankumar** [comment]
@acacha 

https://user-images.githubusercontent.com/3350098/36427860-45b5efd0-161c-11e8-8983-7b96e962308c.png

try like this

**Comment by acacha** [comment]
Yeah thanks that's the problem.

When CLI wizard asks for the id I always think it proposes a default value so I always accept without entering any value.

So maybe if it's mandatory it could be reasonable to avoid CLI permitting a void value..

**Comment by cairinmichie** [comment]
@acacha Good point. The vuetify cli's are being moved to support vue cli 3. will update this when that's ready.
