### ISSUE TITLE
Not a cordova based project

### ISSUE THREAD

**Issue by Oluwatemilorun** [vuetifyjs/cordova#5]
while running `cordova platform add android` error comes up 

`Unhandled promise rejection (rejection id: 1): CordovaError: Current working directory is not a Cordova-based project.`

**Comment by ksankumar** [comment]
Me too getting same issue

**Comment by cairinmichie** [comment]
@Oluwatemilorun @ksankumar what platform are you using? I have only tested it on mac and it still works for me. So I think it may have something to do with your cordova configuration/ OS.

**Comment by ksankumar** [comment]
I am using Windows 10

**Comment by cairinmichie** [comment]
Okay, try again using the updated instructions. I think you guys were initialising the pwa and not the cordova template. Also, make sure that all the directories in the template folder are present in your new project, otherwise cordova won't recognise it as a cordova project.

Please can someone confirm that the updated version works on windows as well.

**Comment by ksankumar** [comment]
@cairinmichie Awesome. You made it. 

<img width="784" alt="cmd1" src="https://user-images.githubusercontent.com/3350098/36427860-45b5efd0-161c-11e8-8983-7b96e962308c.png">
<img width="897" alt="cmd2" src="https://user-images.githubusercontent.com/3350098/36427861-45c1ce4a-161c-11e8-8de1-8228c41015f1.png">
<img width="895" alt="cmd3" src="https://user-images.githubusercontent.com/3350098/36427862-45ce7dde-161c-11e8-9028-42d025e5e159.png">
This is what i followed and works great.

Thanks Again

**Comment by Oluwatemilorun** [comment]
cordova now recognizes it. But after adding platform `browser` and `cordova run browser` it shows the default cordova screen and not that of vueify as shown when `npm run dev`

Any work around this?

**Comment by Oluwatemilorun** [comment]
@ksankumar was it the cordova default that showed?

**Comment by cairinmichie** [comment]
Did you `npm run build` first? Also, not sure why you would want to do that as you won't have hot reloading. 

You can also try `npm run browser`.

**Comment by ksankumar** [comment]
@Oluwatemilorun Where you asking. try my screenshot

**Comment by Oluwatemilorun** [comment]
Tried it...but its still showing the default cordova page

![screenshot 3](https://user-images.githubusercontent.com/20941086/36430844-6511d440-1656-11e8-9e0a-9c132e27b898.png)

**Comment by cairinmichie** [comment]
@Oluwatemilorun what are you trying to achieve man? If you want to run the app in the browser use webpack or PWA templates. You don't need cordova for that.

And just use the dev server for testing in the browser.

**Comment by cairinmichie** [comment]
Closing this issue as the original issue has been fixed.
