### ISSUE TITLE
Not a Cordova-based project in webpack 4

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/cordova#8]
When upgrade to webpack 4 getting below error

npm run android
(node:10136) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Current working directory is not a Cordova-based project.

(node:10136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cairinmichie** [comment]
You need to run `cordova platform add android` before you can run `npm run
android`.

If you still get the error make sure you have all the directories that are
in the template folder.

**Comment by cairinmichie** [comment]
You need to run `cordova platform add android` before you can run `npm run
android`.

If you still get the error make sure you have all the directories that are
in the template folder.

**Comment by ksankumar** [comment]
Working fine with webpack 2.6.1, when i upgrade webpack 4getting issue
<img width="960" alt="error" src="https://user-images.githubusercontent.com/3350098/37462667-268d12a4-2829-11e8-93d5-ef5462528591.png">

**Comment by cairinmichie** [comment]
You don't have the `www` directory. Try  `mkdir www` and then `cordova platform add android`

**Comment by cairinmichie** [comment]
You need all the directories because cordova is dumb and won't dynamically create them when adding platforms, because it normally does that during the init command. But we're skipping that, so you need to make sure all the directories are there.

**Comment by ksankumar** [comment]
This is what i changed in my code and works fine with webpack 4+, Please correct me is there anything wrong.

**webpack.prod.conf.js**
`
var fs = require('fs')
var path = require('path')
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
var SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin')
var loadMinified = require('./load-minified')
var UglifyJsPlugin = require('uglifyjs-webpack-plugin')


var env = config.build.env

var webpackConfig = merge(baseWebpackConfig, {
  mode: 'production',
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true
    })
  },
  devtool: config.build.productionSourceMap ? '#source-map' : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  optimization: {
    minimizer: [
      // we specify a custom UglifyJsPlugin here to get source maps in production
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        uglifyOptions: {
          compress: false,
          ecma: 6,
          mangle: true
        },
        sourceMap: true
      })
    ]
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({ options: {} }),
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    // new webpack.optimize.UglifyJsPlugin({
    //   compress: {
    //     warnings: false
    //   },
    //   sourceMap: true
    // }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    // Compress extracted CSS. We are using this plugin so that possible
    // duplicated CSS from different components can be deduped.
    new OptimizeCSSPlugin({
      cssProcessorOptions: {
        safe: true
      }
    }),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency',
      serviceWorkerLoader: `<script>${loadMinified(path.join(__dirname,
        './service-worker-prod.js'))}</script>`
    }),
    // split vendor js into its own file
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'vendor',
    //   minChunks: function (module, count) {
    //     // any required modules inside node_modules are extracted to vendor
    //     return (
    //       module.resource &&
    //       /\.js$/.test(module.resource) &&
    //       module.resource.indexOf(
    //         path.join(__dirname, '../node_modules')
    //       ) === 0
    //     )
    //   }
    // }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'manifest',
    //   chunks: ['vendor']
    // }),
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
    ]),
    // service worker caching
    new SWPrecacheWebpackPlugin({
      cacheId: 'my-vue-app',
      filename: 'service-worker.js',
      staticFileGlobs: ['dist/**/*.{js,html,css}'],
      minify: true,
      stripPrefix: 'dist/'
    })
  ]
})

if (config.build.productionGzip) {
  var CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}

module.exports = webpackConfig
`
**package.json**
<img width="960" alt="package-json-diff" src="https://user-images.githubusercontent.com/3350098/37466072-425a4a24-2833-11e8-9c3e-084536b3ee03.png">

**Comment by cairinmichie** [comment]
It's a single block of code, I have no idea what you changed. You are more than welcome to make a PR though.

**Comment by ksankumar** [comment]
<img width="960" alt="change1" src="https://user-images.githubusercontent.com/3350098/37466477-40bc7006-2834-11e8-9a86-02d3dfc825c7.png">

<img width="960" alt="change2" src="https://user-images.githubusercontent.com/3350098/37466492-45b0df8e-2834-11e8-9dfc-32249a0e7023.png">

<img width="960" alt="change3" src="https://user-images.githubusercontent.com/3350098/37466500-4b313ddc-2834-11e8-9a73-603c62fcddd2.png">

**Comment by ksankumar** [comment]
development-config change
<img width="960" alt="change4" src="https://user-images.githubusercontent.com/3350098/37466615-9286d912-2834-11e8-9997-57ab3eb9c3b8.png">

**Comment by cairinmichie** [comment]
Have you tested your new config on earlier versions of webpack?

**Comment by ksankumar** [comment]
I thought to go with that, but i am wondering that will affect cordova bundle.

If you don't mind, Can you you share me the link for earlier versions of webpack? I ll play with that and make a PR if works fine..

**Comment by cairinmichie** [comment]
`vue init vuetifyjs/cordova my-project`

**Comment by cairinmichie** [comment]
Or just update webpack in your PR I guess.

**Comment by ksankumar** [comment]
All above changes i done just morning(1hr back) (i m in EST time zone).
Created new project and makes changes. Those changes only i attached with screenshot.

i thought you mean earlier versions of webpack is like webpack -4 cofig :).
 I miss understood

**Comment by ksankumar** [comment]
If i update webpack-4 , i need to make changes above i mentioned screenshot

**Comment by cairinmichie** [comment]
Cool do that, and you can remove the code you commented out if it's not needed.

**Comment by ksankumar** [comment]
sure. But i'm very new to webpack, so i don't know whether i commented code needed or not, especially CommonChuckPlugin blocks. Anyhow i ll do that, please correct me  is there anything wrong. 

I ll raise PR on 1PM EST once i back to home for lunch :)

**Comment by ksankumar** [comment]
@cairinmichie  Created PR

**Comment by superrandres** [comment]
Hi guys, it would be nice if this template is updated, so that the application's performance is optimal, especially on mobile phones. @cairinmichie

**Comment by canhkieu** [comment]
It's neccessary to update this template. @cairinmichie

**Comment by cairinmichie** [comment]
Done. Sorry for the delay.
